-- ==========================================
-- УСТАНОВКА ТАБЛИЦ ДЛЯ МОДУЛЯ FLOORPLAN
-- ==========================================

-- 1. ТАБЛИЦЫ

-- Таблица зданий
CREATE TABLE BUILDING (
    ID_BUILDING INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    FLOORS_COUNT INTEGER DEFAULT 1
);

-- Таблица планов
CREATE TABLE FLOORPLAN (
    ID_FLOORPLAN INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    IMAGE VARCHAR(255) NOT NULL,
    WIDTH INTEGER DEFAULT 800,
    HEIGHT INTEGER DEFAULT 600,
    ID_BUILDING INTEGER DEFAULT 1,
    FLOOR_NUMBER INTEGER DEFAULT 1,
    FLOOR_NAME VARCHAR(50),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица точек на плане
CREATE TABLE FLOORPLAN_POINT (
    ID_POINT INTEGER NOT NULL,
    ID_FLOORPLAN INTEGER NOT NULL,
    X_POS FLOAT DEFAULT 0,
    Y_POS FLOAT DEFAULT 0,
    ID_DEV INTEGER,
    POINT_TYPE VARCHAR(20) DEFAULT 'door',
    LABEL VARCHAR(100)
);

COMMIT;
-- 2. ПЕРВИЧНЫЕ КЛЮЧИ

ALTER TABLE BUILDING ADD CONSTRAINT PK_BUILDING PRIMARY KEY (ID_BUILDING);
ALTER TABLE FLOORPLAN ADD CONSTRAINT PK_FLOORPLAN PRIMARY KEY (ID_FLOORPLAN);
ALTER TABLE FLOORPLAN_POINT ADD CONSTRAINT PK_FLOORPLAN_POINT PRIMARY KEY (ID_POINT);

COMMIT;

-- 3. ВНЕШНИЕ КЛЮЧИ

ALTER TABLE FLOORPLAN ADD CONSTRAINT FK_FLOORPLAN_BUILDING FOREIGN KEY (ID_BUILDING) REFERENCES BUILDING(ID_BUILDING);

ALTER TABLE FLOORPLAN_POINT ADD CONSTRAINT FK_FLOORPLAN_POINT FOREIGN KEY (ID_FLOORPLAN) REFERENCES FLOORPLAN(ID_FLOORPLAN) ON DELETE CASCADE;
	
	COMMIT;

-- 4. ГЕНЕРАТОРЫ

CREATE GENERATOR GEN_BUILDING_ID;
CREATE GENERATOR GEN_FLOORPLAN_ID;
CREATE GENERATOR GEN_FLOORPLAN_POINT_ID;

COMMIT;

-- 5. ТРИГГЕРЫ
--TRG_BUILDING_BI
SET TERM ^ ;
CREATE TRIGGER TRG_BUILDING_BI FOR BUILDING
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_BUILDING IS NULL) THEN
        NEW.ID_BUILDING = GEN_ID(GEN_BUILDING_ID, 1);
END
^
SET TERM ; ^

--TRG_FLOORPLAN_BI
SET TERM ^ ;
CREATE TRIGGER TRG_FLOORPLAN_BI FOR FLOORPLAN
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_FLOORPLAN IS NULL) THEN
        NEW.ID_FLOORPLAN = GEN_ID(GEN_FLOORPLAN_ID, 1);
END
^
SET TERM ; ^

--TRG_FLOORPLAN_POINT_BI
SET TERM ^ ;
CREATE TRIGGER TRG_FLOORPLAN_POINT_BI FOR FLOORPLAN_POINT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_POINT IS NULL) THEN
        NEW.ID_POINT = GEN_ID(GEN_FLOORPLAN_POINT_ID, 1);
END
^
SET TERM ; ^


-- 6. НАЧАЛЬНЫЕ ДАННЫЕ

INSERT INTO BUILDING (ID_BUILDING, NAME, ADDRESS, FLOORS_COUNT) 
VALUES (1, 'Главное здание', 'г. Москва, ул. Примерная, д. 1', 5);

-- Сброс генераторов для начальных данных
SET GENERATOR GEN_BUILDING_ID TO 1;

COMMIT;