-- ==========================================
-- УДАЛЕНИЕ ТАБЛИЦ МОДУЛЯ FLOORPLAN
-- ==========================================

-- Удаляем внешние ключи
ALTER TABLE FLOORPLAN_POINT DROP CONSTRAINT FK_FLOORPLAN_POINT;
ALTER TABLE FLOORPLAN DROP CONSTRAINT FK_FLOORPLAN_BUILDING;

-- Удаляем таблицы
DROP TABLE FLOORPLAN_POINT;
DROP TABLE FLOORPLAN;
DROP TABLE BUILDING;

-- Удаляем генераторы
DROP GENERATOR GEN_FLOORPLAN_POINT_ID;
DROP GENERATOR GEN_FLOORPLAN_ID;
DROP GENERATOR GEN_BUILDING_ID;

-- Удаляем триггеры
DROP TRIGGER TRG_FLOORPLAN_POINT_BI;
DROP TRIGGER TRG_FLOORPLAN_BI;
DROP TRIGGER TRG_BUILDING_BI;