-- ==========================================
-- ОБНОВЛЕНИЕ С V1 ДО V2
-- ==========================================

-- Добавляем новые поля в FLOORPLAN
ALTER TABLE FLOORPLAN ADD ID_BUILDING INTEGER DEFAULT 1;
ALTER TABLE FLOORPLAN ADD FLOOR_NUMBER INTEGER DEFAULT 1;
ALTER TABLE FLOORPLAN ADD FLOOR_NAME VARCHAR(50);

-- Создаем таблицу BUILDING
CREATE TABLE BUILDING (
    ID_BUILDING INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    FLOORS_COUNT INTEGER DEFAULT 1
);

ALTER TABLE BUILDING ADD CONSTRAINT PK_BUILDING PRIMARY KEY (ID_BUILDING);
ALTER TABLE FLOORPLAN ADD CONSTRAINT FK_FLOORPLAN_BUILDING
    FOREIGN KEY (ID_BUILDING) REFERENCES BUILDING(ID_BUILDING);

-- Создаем генератор для BUILDING
CREATE GENERATOR GEN_BUILDING_ID;

-- Триггер для BUILDING
SET TERM ^ ;
CREATE TRIGGER TRG_BUILDING_BI FOR BUILDING
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID_BUILDING IS NULL) THEN
        NEW.ID_BUILDING = GEN_ID(GEN_BUILDING_ID, 1);
END^
SET TERM ; ^

-- Добавляем начальное здание
INSERT INTO BUILDING (ID_BUILDING, NAME, ADDRESS, FLOORS_COUNT) 
VALUES (1, 'Главное здание', 'г. Москва, ул. Примерная, д. 1', 5);

-- Обновляем существующие планы
UPDATE FLOORPLAN SET ID_BUILDING = 1, FLOOR_NUMBER = 1;

-- Сбрасываем генератор
SET GENERATOR GEN_BUILDING_ID TO 1;